### ISSUE TITLE
Drop kubernetes support

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/cg-harden-boshrelease#44]
We have special config for kubernetes VMs here. We should drop it. This should be fine to do any time after our next kubernetes release

**Comment by karareinsel** [comment]
@soutenniza to confirm with @ChrisMcGowan the estimated level of effort. If it's small LOE, then we'll do it this week.

**Comment by ChrisMcGowan** [comment]
https://github.com/cloud-gov/cg-harden-boshrelease/pull/45
